service: serverless-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-east-1:559792203405:table/*"
  environment:
    TABLE_ZIPS: zips
    TABLE_REPS: reps
    TABLE_SENS: sens

functions:
  get_district_by_zip:
    handler: handler.get_district_by_zip
    events:
      - http:
          path: zips/{zipcode}
          method: GET
          cors: true
  get_rep_by_district:
    handler: handler.get_rep_by_district
    events:
      - http:
          path: reps/district/{district}
          method: GET
          cors: true
  get_sen_by_state:
    handler: handler.get_sen_by_state
    events:
      - http:
          path: sens/state/{state}
          method: GET
          cors: true
