service: serverless-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-east-1:559792203405:table/*"
  environment:
    TABLE_ZIPS: zips
    TABLE_REPS: reps
    TABLE_SENS: sens

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true
  getZip:
    handler: handler.getZip
    events:
      - http:
          path: zips/{zipcode}
          method: GET
          cors: true
  getRepById:
    handler: handler.getRepById
    events:
      - http:
          path: reps/district/{id}
          method: GET
          cors: true
  getSenById:
    handler: handler.getSenById
    events:
      - http:
          path: sens/district/{id}
          method: GET
          cors: true
